### ISSUE TITLE
Unable to install package with pip

### ISSUE THREAD

**Issue by particle6** [amzn/login-and-pay-with-amazon-sdk-python#2]
Hi,

Installing the package with pip no longer seems to be working.

```
$ sudo pip3 install pay_with_amazon
```

Getting this response when attempting to install:
`
Collecting pay_with_amazon==1.0.1 (from -r requirements/base.txt (line 46))
Could not find a version that satisfies the requirement pay_with_amazon==1.0.1 (from -r requirements/base.txt (line 46)) (from versions: )
No matching distribution found for pay_with_amazon==1.0.1 (from -r requirements/base.txt (line 46))
`

**Comment by dbrent-amazon** [comment]
Hello!

We apologize for that. We recently updated the version and didn't upload the tarball to PyPi. Can you please try again and let us know if you are able to?

Thanks!

**Comment by islandskater43** [comment]
Closing this. Please reopen if it is still an issue!

**Comment by alex108** [comment]
This issue is happening again in Python 3.6 with pip 18.0. There are currently [no tarballs](https://pypi.org/simple/amazon-pay/) in PyPI.

**Comment by bjguillot** [comment]
Thanks for bringing this to our attention.

The amazon_pay-2.5.0 tarball is now there.
